spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/integrator}
    username: ${DATABASE_USERNAME:integrator}
    password: ${DATABASE_PASSWORD:integrator}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_SENDER}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

userToken:
  expiration-window: 30

ui:
  base-url: http://localhost:4200
  reset-password : /reset-password