
spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/integrator}
    username: ${DATABASE_USERNAME:integrator}
    password: ${DATABASE_PASSWORD:integrator}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: <SECRET_SHOULD_BE_CHANGED>

#logging:
#  level:
#    org.springframework: TRACE

ui:
  base-url: http://localhost:4200
  reset-password : /reset-password