server:
  servlet:
    context-path: /uaa/api

spring:
  datasource:
    url: jdbc:mysql://integrator-database-do-user-12394181-0.c.db.ondigitalocean.com:25060/integrator
    username: doadmin
    password: AVNS_O5ZBKWlbQSU9AdUm75J
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_SENDER}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

userToken:
  expiration-window: 30