INSERT INTO users (created_by,
                   created_date,
                   last_modified_by,
                   last_modified_date,
                   email,
                   name,
                   password,
                   surname,
                   username)
VALUES ('SYSTEM',
        '2024-02-08 23:35:14.000000',
        'SYSTEM',
        '2024-02-08 23:35:14.000000',
        'g.kaanalkim@gmail.com',
        'Guner Kaan',
        '1234',
        'Alkim',
        'kaanalkim');